/**
 * Builds public/icons/sprite.svg from src/components/icon-data.ts (Tabler Icons, MIT),
 * src/components/icon-data-produce.ts (glyphs drawn for this shop) and
 * src/components/icon-data-category.ts (coloured category art drawn for this shop).
 * Pages then reference an icon with <use href="/icons/sprite.svg?v=…#name"> — ~80 bytes per icon
 * instead of repeating the path data in the HTML *and* the RSC payload (it was ~40% of the home
 * page). Run after adding icons: `npm run icons --workspace=apps/web`.
 */
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
/** Both sets go into one sprite: the Tabler icons and the produce glyphs drawn for this shop. */
const readSet = (file) => {
  const src = readFileSync(join(root, file), 'utf8');
  const body = src.slice(src.indexOf('= {') + 2, src.lastIndexOf('};') + 1);
  // The produce file is written as readable JS (single quotes, unquoted keys), not JSON.
  return JSON.parse(
    body
      // drop // line comments (path data never contains "//")
      .replace(/^\s*\/\/.*$/gm, '')
      .replace(/([{,]\s*)'([^']+)'\s*:/g, '$1"$2":')
      .replace(/([{,]\s*)([A-Za-z_][\w-]*)\s*:/g, '$1"$2":')
      .replace(/'/g, '"')
      .replace(/,(\s*[}\]])/g, '$1'),
  );
};
/*
 * Two families, two files — and the split is the point.
 *
 * Line icons are drawn on a 24-unit box and take their colour from `currentColor`; the coloured
 * art is drawn on a 64-unit box and carries its own fills. They used to share one sprite, which was
 * right while every category rendered as a drawing. Now the rail shows photographs of real shops
 * and the drawings are only a fallback for what the shopkeeper has not photographed yet — so
 * shipping all of them cost every visitor most of an 82 KB download to show a handful of UI arrows.
 *
 * A browser fetches a sprite only when something on the page actually references it, so keeping the
 * colour art in its own file means a page with no fallback drawing never asks for it at all, and a
 * page with one pays for it once. The line icons are on every page and stay in the main sprite.
 */
const line = { ...readSet('src/components/icon-data.ts'), ...readSet('src/components/icon-data-produce.ts') };
const art = { ...readSet('src/components/icon-data-category.ts'), ...readSet('src/components/icon-data-product.ts') };
const esc = (v) => String(v).replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/</g, '&lt;');
const symbol = (box) => ([name, nodes]) => {
  const inner = nodes.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${esc(v)}"`).join(' ')}/>`).join('');
  return `<symbol id="${name}" viewBox="0 0 ${box} ${box}">${inner}</symbol>`;
};
const wrap = (credit, body) => `<svg xmlns="http://www.w3.org/2000/svg"><!-- ${credit} -->${body}</svg>\n`;
const lineSvg = wrap('Tabler Icons (MIT) © Paweł Kuna — tabler.io; produce glyphs drawn for Fatanpur Bazaar', Object.entries(line).map(symbol(24)).join(''));
const artSvg = wrap('Category and product art drawn for Fatanpur Bazaar', Object.entries(art).map(symbol(64)).join(''));
writeFileSync(join(root, 'public/icons/sprite.svg'), lineSvg);
writeFileSync(join(root, 'public/icons/art.svg'), artSvg);
const hash = (s) => createHash('sha256').update(s).digest('hex').slice(0, 10);
const v = hash(lineSvg);
const av = hash(artSvg);
const names = Object.keys(line).sort();
const artNames = Object.keys(art).sort();
writeFileSync(
  join(root, 'src/components/icon-sprite.ts'),
  `// GENERATED by scripts/icon-sprite.mjs — do not edit by hand.\nexport const SPRITE_URL = '/icons/sprite.svg?v=${v}';\nexport const ART_URL = '/icons/art.svg?v=${av}';\nexport const ICON_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(names)});\nexport const ART_NAMES: ReadonlySet<string> = new Set(${JSON.stringify(artNames)});\n`,
);
console.log(`sprite: ${names.length} line icons, ${lineSvg.length} bytes, v=${v}`);
console.log(`art:    ${artNames.length} colour art, ${artSvg.length} bytes, v=${av}`);
